<?php
/**
 * @file
 * Code for the Izarra Config feature.
 */

include_once 'izarra_config.features.inc';

/**
 * Implements hook_block_info().
 */
function izarra_config_block_info() {
	$blocks = array();

	$blocks['izarra_site_slogan'] = array(
			'info' => t('Izarra site slogan'),
			'cache' => DRUPAL_NO_CACHE,
	);

	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function izarra_config_block_view($delta = '') {
	switch ($delta) {
		case 'izarra_site_slogan':
			$block['subject'] = '';
			$variables['site_slogan'] = filter_xss_admin(variable_get('site_slogan', ''));
			$block['content'] = theme('izarra_site_slogan', $variables);
			return $block;
			break;
	}
}

/**
 * Implements hook_theme().
 */
function izarra_config_theme() {
	return array(
		'izarra_site_slogan' => array(
				'variables' => array('site_slogan' => NULL),
				'file' => 'izarra_config.theme.inc',
		),
	);
}