<?php
/**
 * @file
 * izarra_products.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function izarra_products_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Jauve, Vert et 54',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'f307a3cf-43bc-494e-9597-a2633e14e241',
  'type' => 'page',
  'language' => 'fr',
  'created' => 1398698409,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '29513c5f-1fef-4e8c-92ba-369a134aec5e',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Curabitur pulvinar, est et blandit ornare, lacus enim condimentum dolor, in iaculis enim urna eget eros! Duis imperdiet posuere purus at mollis. Mauris quis risus vel dolor molestie lacinia sed in ligula. Quisque at bibendum dui! Etiam a diam eu odio egestas sodales eget ac lectus. Aenean quis fringilla urna, et elementum dolor. Sed sagittis mauris interdum odio tristique, sit amet congue tellus tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse diam tellus, convallis vel placerat ac, rhoncus vel urna. Morbi vel ante cursus, vehicula erat a, adipiscing leo. Sed eget pellentesque nibh.</p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p>Curabitur pulvinar, est et blandit ornare, lacus enim condimentum dolor, in iaculis enim urna eget eros! Duis imperdiet posuere purus at mollis. Mauris quis risus vel dolor molestie lacinia sed in ligula. Quisque at bibendum dui! Etiam a diam eu odio egestas sodales eget ac lectus. Aenean quis fringilla urna, et elementum dolor. Sed sagittis mauris interdum odio tristique, sit amet congue tellus tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse diam tellus, convallis vel placerat ac, rhoncus vel urna. Morbi vel ante cursus, vehicula erat a, adipiscing leo. Sed eget pellentesque nibh.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_bg_image' => array(
    'und' => array(
      0 => array(
        'fid' => 22,
        'uid' => 1,
        'filename' => 'mojito.jpg',
        'uri' => 'public://mojito.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 172105,
        'status' => 1,
        'timestamp' => 1398701460,
        'uuid' => 'e0860335-d1a1-453a-8cb7-cd435e9db409',
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1080,
      ),
    ),
  ),
  'field_subtitle' => array(),
  'metatags' => array(),
  'name' => 'superadmin',
  'picture' => 0,
  'data' => 'b:0;',
  'weight_weight' => 0,
  'date' => '2014-04-28 17:20:09 +0200',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Izarra jaune',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '6b4479fa-8ef3-46af-86c5-9325c1e63ae5',
  'type' => 'product',
  'language' => 'fr',
  'created' => 1398703246,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2c0cd533-df0c-4a01-a8fc-4754a92c06eb',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Cras facilisis cursus faucibus. Donec gravida tellus eu nunc semper tristique. Nullam non ligula ut augue tincidunt lacinia eget a leo. Sed quis egestas velit. Fusce faucibus vestibulum sollicitudin. Fusce quam ante, vulputate vel dolor vitae, malesuada gravida magna. Morbi placerat turpis vitae quam iaculis, sit amet feugiat tortor pulvinar. Proin est tortor, fermentum eget ipsum et, condimentum pharetra nulla. Nullam bibendum tincidunt blandit. Proin suscipit nulla vitae diam dictum aliquam. Phasellus commodo felis a vestibulum elementum. Etiam adipiscing tortor ac tellus pharetra, rhoncus elementum enim hendrerit.</p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p>Cras facilisis cursus faucibus. Donec gravida tellus eu nunc semper tristique. Nullam non ligula ut augue tincidunt lacinia eget a leo. Sed quis egestas velit. Fusce faucibus vestibulum sollicitudin. Fusce quam ante, vulputate vel dolor vitae, malesuada gravida magna. Morbi placerat turpis vitae quam iaculis, sit amet feugiat tortor pulvinar. Proin est tortor, fermentum eget ipsum et, condimentum pharetra nulla. Nullam bibendum tincidunt blandit. Proin suscipit nulla vitae diam dictum aliquam. Phasellus commodo felis a vestibulum elementum. Etiam adipiscing tortor ac tellus pharetra, rhoncus elementum enim hendrerit.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_bg_image' => array(
    'und' => array(
      0 => array(
        'fid' => 24,
        'uid' => 1,
        'filename' => 'image-test_fullhd.jpg',
        'uri' => 'public://image-test_fullhd_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 16976,
        'status' => 1,
        'timestamp' => 1398703246,
        'uuid' => '499f291f-4f76-46a2-a0d3-05b83e648a2e',
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1080,
      ),
    ),
  ),
  'field_subtitle' => array(),
  'metatags' => array(),
  'name' => 'superadmin',
  'picture' => 0,
  'data' => 'b:0;',
  'weight_weight' => 0,
  'date' => '2014-04-28 18:40:46 +0200',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Izarra 54',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'c048328e-bf19-4220-a532-837c18177a2f',
  'type' => 'product',
  'language' => 'fr',
  'created' => 1398759141,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b9281cec-5628-44f5-8c0f-b66fe8872282',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>In ut tincidunt metus, vel facilisis felis. Phasellus id pellentesque mi. In ultrices mauris eu rhoncus molestie. Quisque dapibus dui eu lorem adipiscing pharetra. Proin ac tempus orci, sed pretium sem. Ut mattis mauris id accumsan imperdiet. Donec convallis volutpat purus et vehicula. Nam sit amet iaculis odio. Ut eu lacinia est.</p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p>In ut tincidunt metus, vel facilisis felis. Phasellus id pellentesque mi. In ultrices mauris eu rhoncus molestie. Quisque dapibus dui eu lorem adipiscing pharetra. Proin ac tempus orci, sed pretium sem. Ut mattis mauris id accumsan imperdiet. Donec convallis volutpat purus et vehicula. Nam sit amet iaculis odio. Ut eu lacinia est.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_bg_image' => array(
    'und' => array(
      0 => array(
        'fid' => 25,
        'uid' => 1,
        'filename' => 'image-test_fullhd.jpg',
        'uri' => 'public://image-test_fullhd_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 16976,
        'status' => 1,
        'timestamp' => 1398759141,
        'uuid' => 'b0550a1c-4f35-44fb-9278-ea09151e773f',
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1080,
      ),
    ),
  ),
  'field_subtitle' => array(),
  'metatags' => array(),
  'name' => 'superadmin',
  'picture' => 0,
  'data' => 'b:0;',
  'weight_weight' => 0,
  'date' => '2014-04-29 10:12:21 +0200',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Izarra vert',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'a1707760-0fe5-434b-892f-a52ad984f373',
  'type' => 'product',
  'language' => 'fr',
  'created' => 1398702603,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f013d4ba-4b4f-4e0b-8b17-fdad13301330',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Morbi scelerisque tempus arcu, eu facilisis quam viverra auctor? Nullam a tellus a augue ultrices commodo. Nam et tristique risus, sit amet scelerisque dui? Morbi aliquet enim quis ipsum interdum tincidunt. Nullam tempus vulputate arcu, quis pharetra elit tristique id. Phasellus gravida id dui et posuere. Mauris nunc turpis, pretium quis volutpat in, imperdiet ut nunc! Morbi gravida imperdiet elit, vel placerat enim gravida quis. Nam vulputate est sed mi pretium volutpat ac quis ipsum. Praesent vitae purus et massa hendrerit euismod id eu nunc. Aliquam erat volutpat. Sed tempor tortor eu nibh facilisis, ac fermentum libero pulvinar? In dignissim placerat gravida. Vestibulum semper metus a ultricies luctus.</p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p>Morbi scelerisque tempus arcu, eu facilisis quam viverra auctor? Nullam a tellus a augue ultrices commodo. Nam et tristique risus, sit amet scelerisque dui? Morbi aliquet enim quis ipsum interdum tincidunt. Nullam tempus vulputate arcu, quis pharetra elit tristique id. Phasellus gravida id dui et posuere. Mauris nunc turpis, pretium quis volutpat in, imperdiet ut nunc! Morbi gravida imperdiet elit, vel placerat enim gravida quis. Nam vulputate est sed mi pretium volutpat ac quis ipsum. Praesent vitae purus et massa hendrerit euismod id eu nunc. Aliquam erat volutpat. Sed tempor tortor eu nibh facilisis, ac fermentum libero pulvinar? In dignissim placerat gravida. Vestibulum semper metus a ultricies luctus.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_bg_image' => array(
    'und' => array(
      0 => array(
        'fid' => 23,
        'uid' => 1,
        'filename' => 'image-test_fullhd.jpg',
        'uri' => 'public://image-test_fullhd.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 16976,
        'status' => 1,
        'timestamp' => 1398702603,
        'uuid' => '7e5b063f-908f-4ce9-8b0e-9e272fbf7300',
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1080,
      ),
    ),
  ),
  'field_subtitle' => array(),
  'metatags' => array(),
  'name' => 'superadmin',
  'picture' => 0,
  'data' => 'b:0;',
  'weight_weight' => 0,
  'date' => '2014-04-28 18:30:03 +0200',
);
  return $nodes;
}
